= My Git Cookbook
:doctype: book
:publication-type: book
:toc: left
:source-highlighter: highlight.js 
:source-language: bash 
:icons: font

== Github

=== Generate personal access token

https://stackoverflow.com/questions/68775869/support-for-password-authentication-was-removed-please-use-a-personal-access-to[Stackoverflow]

1. Goto https://github.com/settings/tokens/new
2. Select the token permissions, for example, `repo` (including repo::status ...) and then generate the token string
3. Under your repository,
+
[source, bash]
git remote set-url origin https://<token_string>@github.com/<username>/<repo_name>
+
where
* `<token_string>` is the token string from the previous step
* `<username>` is your Github username
* `<repo_name>` is your Github repository name

== Rebase and Merge

Say your source branch is `feature/add_awesome_feature` and you want to rebase it on target branch, `main`, and merge to target branch

1. Squash your commits (For example, there are 7 commits after branch point with main branch)
+
[source]
git rebase -i HEAD~7

* Change branches other than the first to `s` (which means squash)

2. Rebase on your target branch (e.g. main)
+
[source]
git rebase main

3. Check out your target branch
+
[source]
git checkout main

4. Merge your rebased branch to target branch
+
[source]
------
git merge feature/add_awesome_feature
------
Since you already rebase your source branch, it would be fast-forward without creating new nodes.

=== Reference

https://backlog.com/git-tutorial/tw/stepup/stepup1_4.html[分支的合併]

https://backlog.com/git-tutorial/tw/stepup/stepup2_8.html[使用 rebase 合併]


== Unstage delete

https://stackoverflow.com/questions/9477702/undo-delete-in-git[Stackoverflow]

[source,bash]
git checkout -f


== Undo last commit and keep the change

https://stackoverflow.com/questions/15772134/can-i-delete-a-git-commit-but-keep-the-changes[Stackoverflow]

[source,bash]
git reset HEAD^

== Change last commit message

https://backlog.com/git-tutorial/tw/stepup/stepup7_1.html[backlog]

[source,bash]
Commit --amend

== Rename the folder with the same name in different cases

[source,bash]
git mv sampledir TEMP
git mv TEMP SampleDir
